### ISSUE TITLE
Comprehensive Tutorials Suite

### ISSUE THREAD

**Issue by ennsharma** [oasislabs/tutorials#45]
**What is the problem that you're trying to solve?**
Our current tutorials are limited in showing usage of the Oasis SDK across different frameworks / platforms. This issue is for long-term tracking of developing a richer and more diverse set of tutorials.

Additionally, our current motivating tutorial (Secret Ballot) is long and it may take the average developer considerable amount of time and energy to work through it. The longer term goal should be to have tutorials be modular and more succinct.

**Describe the solution you'd like**

_Client tutorials_
- [x] Vue app tutorial (SecretBallot)
- [ ] React app tutorial
- [ ] Android app tutorial
- [ ] iOS app tutorial
- [ ] Node tutorial

_Server tutorials_
- [x] HelloWorld
- [ ] Basic Rust tutorial
- [x] Basic service tutorial (SecretBallot)
- [x] Service testing tutorial (SecretBallot)
- [ ] Events tutorial
- [ ] Cross-contract calls tutorial

_Note_: Above, Secret Ballot is complete, but perhaps should be separated into several iterative tutorials instead of one long one for aesthetic purposes
